Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -61,7 +61,9 @@ jobs:
           [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
           [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
           nvm install v23
-          npm install
+          echo "Before npm install"
+          npm install --verbose || echo "❌ npm install failed"
+          echo "After npm install"
           echo "h2"
           timeout 120s npm run build -- --debug
           echo "h3" 
